# Generated by Django 6.0.1 on 2026-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacealert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged')], default='NEW', max_length=20),
        ),
    ]
