# Generated by Django 6.0.1 on 2026-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0002_interfacealert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacealert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
