# Generated by Django 6.0.1 on 2026-01-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0003_alter_interfacealert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='interfacealert',
            name='alert_type',
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMPapp.alertlevel')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMPapp.interface')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('description', models.TextField()),
                ('alert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMPapp.alertlevel')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMPapp.interface')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMPapp.metric')),
            ],
        ),
        migrations.DeleteModel(
            name='AlertType',
        ),
        migrations.DeleteModel(
            name='InterfaceAlert',
        ),
    ]
