# Generated by Django 6.0.1 on 2026-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0004_alertlevel_interface_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlevel',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
