# Generated by Django 6.0.1 on 2026-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0005_alertlevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit_of_measure',
            field=models.CharField(max_length=100),
        ),
    ]
