# Generated by Django 6.0.1 on 2026-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMPapp', '0006_alter_metric_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
